export const ADD_CART = "ADD_CART"
export const REMOVE_CART = "REMOVE_CART"
export const CLEAR_CART = "CLEAR_CART"
export const GET_CART = "GET_CART"

export const GET_LOCATION = "GET_LOCATION"
export const USER_LOCATION = "USER_LOCATION"
export const GET_LOCATIONS = "GET_LOCATIONS"
export const LOCATION_HISTORY = "LOCATION_HISTORY"
export const DEL_HISTORY = "DEL_HISTORY"
export const EMPTY_HISTORY = "EMPTY_HISTORY"